# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
    - 3.5
    - 3.4
    - 2.7
env:
    - TWISTED=latest
    - TWISTED=14.0.2
    - TWISTED=15.5.0
    - TWISTED=16.0.0
    - TWISTED=16.1.1
    - TWISTED=16.2.0
    - TWISTED=16.3.2
    - TWISTED=16.4.1
matrix:
    exclude:
        # don't test on earlier version on Python 3, 'trial' is not available before TWISTED=15.4.0
        - python: 3.5
          env: TWISTED=14.0.2
        - python: 3.4
          env: TWISTED=14.0.2


# command to install dependencies
install:
    - pip install -U pip
    - pip install -U -r requirements.txt -r requirements-dev.txt .
    - |
        # Overwrite twisted package for test
        set -e
        [ $TWISTED = latest ] || pip install Twisted==$TWISTED
    - pip install -U tox coveralls coverage

# command to run tests
script:
    - trial txrwlock
    - coverage run --branch --source=txrwlock $(which trial) txrwlock && coverage report -m
    - python setup.py build_sphinx

after_success:
    - "coveralls"

deploy:
    provider: pypi
    user: "Stibbons"
    distributions: sdist bdist_wheel
    password:
        secure: IHSLyza/BoER1mMVlmaNr4EGGv4d6n0TPKZTrMPi4KsW7FuFvEeiVqX5VFHi54L1EMX8fg0gb4to0LjMyo+wVPSLcDxq5me4MSwPYulgSigEPE9ixVI7R+q8GrkURiSdDeH6PV1kKH9iLDNH9fHunC2a+Nkk4vk6WcFPv1cXLOkX+S8GcHpaHd3NL2kykcotw1b7vUOE96i528IXDK9s4OL2+TPymGuphQysEx1Pop4LPrilk3CfGkZTmKwiF9QhBEfuqJu550SUEs30UMlSBmvC4qGZaeeVpwNSWVrz9lpw/VkR/G0hO0Jt4BY1vODsFpzOog/BrV/EIiMiNHtVU83SeJiQLnmNtoRgJ+HYms/vlst63m+XV/7KzcFNTlZu5aa9Icol3JQT3nZJkfGIWafojtYiIA1lLqYmxtNqLEp5gB+huio79KK9vAkPyr/O532EEMK5nJv06nwXuQCGUnC9XB0qPlzszIj3GVMGhLvMywTUTo+pykuPtqCcSsFkt5fs3JQYxn/wZU+fKnGgUivy/FusD9MPGDIU69wuEye59nUhVTT1092FOZf/uraH8w6n/oTnSjQ984U102nZq983O/bDaVs1DKYgrylyvJ6ERanUt8cZSBQ5ksEqbILE9rYJXVmosjkOjcpXrCEsXJ5UQ98JQ22Q7VWeBEbzqIw=
    on:
        all_branches: true\
        condition: $TRAVIS_TAG != "" && $TWISTED == "latest"
